//! Color themes.
//!
//! The effective theme is layered, lowest to highest:
//! 1. the built-in default,
//! 2. `theme = "<name>"` (built-in, or `<config_dir>/vtt/themes/<name>.toml|.conf`),
//!    or `theme_file = "<path>"`,
//! 3. inline `[colors]` from the config,
//! 4. with `adopt_shell_palette`, colors a shell set via OSC 4/10/11/12 (applied at runtime).
//!
//! Theme files are either vtt TOML (the same keys as `[colors]`) or kitty's `key value` format,
//! so any kitty theme, or a file generated by pywal/wallust/matugen, works unchanged.

mod chrome;
mod formats;

use std::path::{Path, PathBuf};

use crate::config::Config;

pub use chrome::{UiColors, mix};
pub use formats::patch_from_osc;
use formats::{load_file, parse_toml, patch_from_table};

pub type Rgb = [u8; 3];

/// A fully resolved theme.
#[derive(Clone, Debug, PartialEq)]
pub struct Theme {
    pub foreground: Rgb,
    pub background: Rgb,
    pub cursor: Rgb,
    pub selection: Rgb,
    /// 256-color table: 0-15 ANSI, 16-231 color cube, 232-255 grayscale.
    pub colors: [Rgb; 256],
    pub accent: Option<Rgb>,
    pub sidebar: Option<Rgb>,
}

/// A partial theme: only the keys a source actually sets.
#[derive(Clone, Debug, Default, PartialEq)]
pub struct Patch {
    pub foreground: Option<Rgb>,
    pub background: Option<Rgb>,
    pub cursor: Option<Rgb>,
    pub selection: Option<Rgb>,
    pub colors: Vec<(u8, Rgb)>,
    pub accent: Option<Rgb>,
    pub sidebar: Option<Rgb>,
}

impl Patch {
    pub fn is_empty(&self) -> bool {
        *self == Patch::default()
    }

    /// Layer `other` on top: its keys win, key by key.
    pub fn merge(&mut self, other: Patch) {
        self.foreground = other.foreground.or(self.foreground);
        self.background = other.background.or(self.background);
        self.cursor = other.cursor.or(self.cursor);
        self.selection = other.selection.or(self.selection);
        self.accent = other.accent.or(self.accent);
        self.sidebar = other.sidebar.or(self.sidebar);
        for (i, c) in other.colors {
            self.colors.retain(|(j, _)| *j != i);
            self.colors.push((i, c));
        }
    }
}

impl Theme {
    pub fn apply(&mut self, p: &Patch) {
        let set = |slot: &mut Rgb, v: Option<Rgb>| {
            if let Some(v) = v {
                *slot = v;
            }
        };
        set(&mut self.foreground, p.foreground);
        set(&mut self.background, p.background);
        set(&mut self.cursor, p.cursor);
        set(&mut self.selection, p.selection);
        for &(i, c) in &p.colors {
            self.colors[i as usize] = c;
        }
        self.accent = p.accent.or(self.accent);
        self.sidebar = p.sidebar.or(self.sidebar);
    }

    pub fn is_light(&self) -> bool {
        luminance(self.background) > 0.5
    }
}

impl Default for Theme {
    fn default() -> Self {
        let mut colors = [[0u8; 3]; 256];
        for (i, c) in colors.iter_mut().enumerate().skip(16) {
            *c = xterm_color(i as u8);
        }
        let mut theme = Theme {
            foreground: [0xcd, 0xd6, 0xf4],
            background: [0x1e, 0x1e, 0x2e],
            cursor: [0xf5, 0xe0, 0xdc],
            selection: [0x58, 0x5b, 0x70],
            colors,
            accent: None,
            sidebar: None,
        };
        let patch = parse_toml(BUILTIN[0].1).expect("built-in default theme parses");
        theme.apply(&patch.0);
        theme
    }
}

/// xterm's default color cube (16-231) and grayscale ramp (232-255).
fn xterm_color(i: u8) -> Rgb {
    match i {
        16..=231 => {
            let i = i - 16;
            let level = |v: u8| if v == 0 { 0 } else { 55 + v * 40 };
            [level(i / 36), level((i / 6) % 6), level(i % 6)]
        }
        232..=255 => {
            let v = 8 + 10 * (i - 232);
            [v, v, v]
        }
        _ => [0, 0, 0],
    }
}

fn luminance([r, g, b]: Rgb) -> f32 {
    (0.2126 * r as f32 + 0.7152 * g as f32 + 0.0722 * b as f32) / 255.0
}

pub const BUILTIN: &[(&str, &str)] = &[
    (
        "default",
        r##"# Catppuccin Mocha
foreground = "#cdd6f4"
background = "#1e1e2e"
cursor = "#f5e0dc"
selection = "#585b70"
ansi = ["#45475a", "#f38ba8", "#a6e3a1", "#f9e2af", "#89b4fa", "#f5c2e7", "#94e2d5", "#bac2de",
        "#585b70", "#f38ba8", "#a6e3a1", "#f9e2af", "#89b4fa", "#f5c2e7", "#94e2d5", "#a6adc8"]
"##,
    ),
    (
        "catppuccin-latte",
        r##"foreground = "#4c4f69"
background = "#eff1f5"
cursor = "#dc8a78"
selection = "#acb0be"
ansi = ["#5c5f77", "#d20f39", "#40a02b", "#df8e1d", "#1e66f5", "#ea76cb", "#179299", "#acb0be",
        "#6c6f85", "#d20f39", "#40a02b", "#df8e1d", "#1e66f5", "#ea76cb", "#179299", "#bcc0cc"]
"##,
    ),
    (
        "gruvbox-dark",
        r##"foreground = "#ebdbb2"
background = "#282828"
cursor = "#ebdbb2"
selection = "#504945"
ansi = ["#282828", "#cc241d", "#98971a", "#d79921", "#458588", "#b16286", "#689d6a", "#a89984",
        "#928374", "#fb4934", "#b8bb26", "#fabd2f", "#83a598", "#d3869b", "#8ec07c", "#ebdbb2"]
[ui]
accent = "#fabd2f"
"##,
    ),
    (
        "tokyo-night",
        r##"foreground = "#c0caf5"
background = "#1a1b26"
cursor = "#c0caf5"
selection = "#33467c"
ansi = ["#15161e", "#f7768e", "#9ece6a", "#e0af68", "#7aa2f7", "#bb9af7", "#7dcfff", "#a9b1d6",
        "#414868", "#f7768e", "#9ece6a", "#e0af68", "#7aa2f7", "#bb9af7", "#7dcfff", "#c0caf5"]
"##,
    ),
];

pub fn themes_dir() -> Option<PathBuf> {
    Config::path().and_then(|p| p.parent().map(|d| d.join("themes")))
}

/// Result of resolving the configured theme.
pub struct Resolved {
    pub theme: Theme,
    /// The theme file in use, if any (watched for live reload).
    pub file: Option<PathBuf>,
}

/// Build the effective theme from the config. Problems are reported on stderr and skipped.
pub fn resolve(config: &Config) -> Resolved {
    let mut theme = Theme::default();
    let mut file = None;

    if let Some(path) = &config.theme_file {
        let path = expand_tilde(path);
        match load_file(&path) {
            Ok(patch) => theme.apply(&patch),
            Err(err) => crate::diag::warn(format!("theme_file {}: {err}", path.display())),
        }
        file = Some(path);
    } else if let Some(name) = &config.theme {
        if let Some((_, src)) = BUILTIN.iter().find(|(n, _)| n == name) {
            theme.apply(&parse_toml(src).expect("built-in theme parses").0);
        } else {
            let found = themes_dir().and_then(|dir| {
                ["toml", "conf"]
                    .iter()
                    .map(|ext| dir.join(format!("{name}.{ext}")))
                    .find(|p| p.is_file())
            });
            match found {
                Some(path) => {
                    match load_file(&path) {
                        Ok(patch) => theme.apply(&patch),
                        Err(err) => crate::diag::warn(format!("theme {}: {err}", path.display())),
                    }
                    file = Some(path);
                }
                None => {
                    let names: Vec<&str> = BUILTIN.iter().map(|(n, _)| *n).collect();
                    crate::diag::warn(format!(
                        "theme `{name}` not found (built-in: {}; or add {name}.toml / {name}.conf to {})",
                        names.join(", "),
                        themes_dir()
                            .map(|d| d.display().to_string())
                            .unwrap_or_default()
                    ));
                }
            }
        }
    }

    match patch_from_table(&config.colors) {
        Ok((patch, warnings)) => {
            for w in warnings {
                crate::diag::warn(format!("[colors]: {w}"));
            }
            theme.apply(&patch);
        }
        Err(err) => crate::diag::warn(format!("[colors]: {err}")),
    }
    Resolved { theme, file }
}

fn expand_tilde(path: &Path) -> PathBuf {
    match path.strip_prefix("~") {
        Ok(rest) => dirs::home_dir()
            .map(|h| h.join(rest))
            .unwrap_or_else(|| path.to_path_buf()),
        Err(_) => path.to_path_buf(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use eframe::egui::Color32;

    #[test]
    fn merging_osc_patches() {
        let mut shell = Patch::default();
        shell.merge(Patch {
            background: Some([1, 1, 1]),
            colors: vec![(1, [9, 9, 9])],
            ..Default::default()
        });
        shell.merge(Patch {
            colors: vec![(1, [8, 8, 8]), (2, [7, 7, 7])],
            ..Default::default()
        });
        assert_eq!(shell.background, Some([1, 1, 1]));
        assert_eq!(shell.colors, vec![(1, [8, 8, 8]), (2, [7, 7, 7])]);
    }

    #[test]
    fn layering_and_ui_derivation() {
        let mut t = Theme::default();
        assert_eq!(t.colors[16], [0, 0, 0]);
        assert_eq!(t.colors[231], [255, 255, 255]);
        t.apply(&parse_toml(BUILTIN[1].1).unwrap().0); // latte
        assert!(t.is_light());
        let ui = UiColors::from_theme(&t);
        assert!(ui.light);
        assert_eq!(ui.accent, Color32::from_rgb(0x1e, 0x66, 0xf5)); // falls back to color4
        // Raised surfaces move toward the foreground, so they get darker on a light theme.
        assert!(ui.raised(0.2).r() < ui.bg.r());
    }
}
