//! Color themes.
//!
//! The effective theme is layered, lowest to highest:
//! 1. the built-in default,
//! 2. `theme = "<name>"` (built-in, or `<config_dir>/vtt/themes/<name>.toml|.conf`),
//!    or `theme_file = "<path>"`,
//! 3. inline `[colors]` from the config,
//! 4. with `adopt_shell_palette`, colors a shell set via OSC 4/10/11/12 (applied at runtime).
//!
//! Theme files are either vtt TOML (the same keys as `[colors]`) or kitty's `key value` format,
//! so any kitty theme, or a file generated by pywal/wallust/matugen, works unchanged.

use std::path::{Path, PathBuf};

use eframe::egui::Color32;

use crate::config::{Config, parse_hex};

pub type Rgb = [u8; 3];

/// A fully resolved theme.
#[derive(Clone, Debug, PartialEq)]
pub struct Theme {
    pub foreground: Rgb,
    pub background: Rgb,
    pub cursor: Rgb,
    pub selection: Rgb,
    /// 256-color table: 0-15 ANSI, 16-231 color cube, 232-255 grayscale.
    pub colors: [Rgb; 256],
    pub accent: Option<Rgb>,
    pub sidebar: Option<Rgb>,
}

/// A partial theme: only the keys a source actually sets.
#[derive(Clone, Debug, Default, PartialEq)]
pub struct Patch {
    pub foreground: Option<Rgb>,
    pub background: Option<Rgb>,
    pub cursor: Option<Rgb>,
    pub selection: Option<Rgb>,
    pub colors: Vec<(u8, Rgb)>,
    pub accent: Option<Rgb>,
    pub sidebar: Option<Rgb>,
}

impl Patch {
    pub fn is_empty(&self) -> bool {
        *self == Patch::default()
    }

    /// Layer `other` on top: its keys win, key by key.
    pub fn merge(&mut self, other: Patch) {
        self.foreground = other.foreground.or(self.foreground);
        self.background = other.background.or(self.background);
        self.cursor = other.cursor.or(self.cursor);
        self.selection = other.selection.or(self.selection);
        self.accent = other.accent.or(self.accent);
        self.sidebar = other.sidebar.or(self.sidebar);
        for (i, c) in other.colors {
            self.colors.retain(|(j, _)| *j != i);
            self.colors.push((i, c));
        }
    }
}

impl Theme {
    pub fn apply(&mut self, p: &Patch) {
        let set = |slot: &mut Rgb, v: Option<Rgb>| {
            if let Some(v) = v {
                *slot = v;
            }
        };
        set(&mut self.foreground, p.foreground);
        set(&mut self.background, p.background);
        set(&mut self.cursor, p.cursor);
        set(&mut self.selection, p.selection);
        for &(i, c) in &p.colors {
            self.colors[i as usize] = c;
        }
        self.accent = p.accent.or(self.accent);
        self.sidebar = p.sidebar.or(self.sidebar);
    }

    pub fn is_light(&self) -> bool {
        luminance(self.background) > 0.5
    }
}

impl Default for Theme {
    fn default() -> Self {
        let mut colors = [[0u8; 3]; 256];
        for (i, c) in colors.iter_mut().enumerate().skip(16) {
            *c = xterm_color(i as u8);
        }
        let mut theme = Theme {
            foreground: [0xcd, 0xd6, 0xf4],
            background: [0x1e, 0x1e, 0x2e],
            cursor: [0xf5, 0xe0, 0xdc],
            selection: [0x58, 0x5b, 0x70],
            colors,
            accent: None,
            sidebar: None,
        };
        let patch = parse_toml(BUILTIN[0].1).expect("built-in default theme parses");
        theme.apply(&patch.0);
        theme
    }
}

/// xterm's default color cube (16-231) and grayscale ramp (232-255).
fn xterm_color(i: u8) -> Rgb {
    match i {
        16..=231 => {
            let i = i - 16;
            let level = |v: u8| if v == 0 { 0 } else { 55 + v * 40 };
            [level(i / 36), level((i / 6) % 6), level(i % 6)]
        }
        232..=255 => {
            let v = 8 + 10 * (i - 232);
            [v, v, v]
        }
        _ => [0, 0, 0],
    }
}

fn luminance([r, g, b]: Rgb) -> f32 {
    (0.2126 * r as f32 + 0.7152 * g as f32 + 0.0722 * b as f32) / 255.0
}

pub const BUILTIN: &[(&str, &str)] = &[
    (
        "default",
        r##"# Catppuccin Mocha
foreground = "#cdd6f4"
background = "#1e1e2e"
cursor = "#f5e0dc"
selection = "#585b70"
ansi = ["#45475a", "#f38ba8", "#a6e3a1", "#f9e2af", "#89b4fa", "#f5c2e7", "#94e2d5", "#bac2de",
        "#585b70", "#f38ba8", "#a6e3a1", "#f9e2af", "#89b4fa", "#f5c2e7", "#94e2d5", "#a6adc8"]
"##,
    ),
    (
        "catppuccin-latte",
        r##"foreground = "#4c4f69"
background = "#eff1f5"
cursor = "#dc8a78"
selection = "#acb0be"
ansi = ["#5c5f77", "#d20f39", "#40a02b", "#df8e1d", "#1e66f5", "#ea76cb", "#179299", "#acb0be",
        "#6c6f85", "#d20f39", "#40a02b", "#df8e1d", "#1e66f5", "#ea76cb", "#179299", "#bcc0cc"]
"##,
    ),
    (
        "gruvbox-dark",
        r##"foreground = "#ebdbb2"
background = "#282828"
cursor = "#ebdbb2"
selection = "#504945"
ansi = ["#282828", "#cc241d", "#98971a", "#d79921", "#458588", "#b16286", "#689d6a", "#a89984",
        "#928374", "#fb4934", "#b8bb26", "#fabd2f", "#83a598", "#d3869b", "#8ec07c", "#ebdbb2"]
[ui]
accent = "#fabd2f"
"##,
    ),
    (
        "tokyo-night",
        r##"foreground = "#c0caf5"
background = "#1a1b26"
cursor = "#c0caf5"
selection = "#33467c"
ansi = ["#15161e", "#f7768e", "#9ece6a", "#e0af68", "#7aa2f7", "#bb9af7", "#7dcfff", "#a9b1d6",
        "#414868", "#f7768e", "#9ece6a", "#e0af68", "#7aa2f7", "#bb9af7", "#7dcfff", "#c0caf5"]
"##,
    ),
];

pub fn themes_dir() -> Option<PathBuf> {
    Config::path().and_then(|p| p.parent().map(|d| d.join("themes")))
}

/// Result of resolving the configured theme.
pub struct Resolved {
    pub theme: Theme,
    /// The theme file in use, if any (watched for live reload).
    pub file: Option<PathBuf>,
}

/// Build the effective theme from the config. Problems are reported on stderr and skipped.
pub fn resolve(config: &Config) -> Resolved {
    let mut theme = Theme::default();
    let mut file = None;

    if let Some(path) = &config.theme_file {
        let path = expand_tilde(path);
        match load_file(&path) {
            Ok(patch) => theme.apply(&patch),
            Err(err) => eprintln!("vtt: theme_file {}: {err}", path.display()),
        }
        file = Some(path);
    } else if let Some(name) = &config.theme {
        if let Some((_, src)) = BUILTIN.iter().find(|(n, _)| n == name) {
            theme.apply(&parse_toml(src).expect("built-in theme parses").0);
        } else {
            let found = themes_dir().and_then(|dir| {
                ["toml", "conf"]
                    .iter()
                    .map(|ext| dir.join(format!("{name}.{ext}")))
                    .find(|p| p.is_file())
            });
            match found {
                Some(path) => {
                    match load_file(&path) {
                        Ok(patch) => theme.apply(&patch),
                        Err(err) => eprintln!("vtt: theme {}: {err}", path.display()),
                    }
                    file = Some(path);
                }
                None => {
                    let names: Vec<&str> = BUILTIN.iter().map(|(n, _)| *n).collect();
                    eprintln!(
                        "vtt: theme `{name}` not found (built-in: {}; or add {name}.toml / {name}.conf to {})",
                        names.join(", "),
                        themes_dir()
                            .map(|d| d.display().to_string())
                            .unwrap_or_default()
                    );
                }
            }
        }
    }

    match patch_from_table(&config.colors) {
        Ok((patch, warnings)) => {
            for w in warnings {
                eprintln!("vtt: [colors]: {w}");
            }
            theme.apply(&patch);
        }
        Err(err) => eprintln!("vtt: [colors]: {err}"),
    }
    Resolved { theme, file }
}

fn expand_tilde(path: &Path) -> PathBuf {
    match path.strip_prefix("~") {
        Ok(rest) => dirs::home_dir()
            .map(|h| h.join(rest))
            .unwrap_or_else(|| path.to_path_buf()),
        Err(_) => path.to_path_buf(),
    }
}

/// Load a theme file: `.toml` is vtt's format, anything else is parsed as kitty's.
pub fn load_file(path: &Path) -> Result<Patch, String> {
    let text = std::fs::read_to_string(path).map_err(|e| e.to_string())?;
    if path.extension().is_some_and(|e| e == "toml") {
        let (patch, warnings) = parse_toml(&text)?;
        for w in warnings {
            eprintln!("vtt: {}: {w}", path.display());
        }
        Ok(patch)
    } else {
        Ok(parse_kitty(&text))
    }
}

/// vtt TOML theme: `foreground`, `background`, `cursor`, `selection`, `ansi = [16 colors]`,
/// `colorN` for any palette index, and `[ui]` with `accent` / `sidebar`.
pub fn parse_toml(text: &str) -> Result<(Patch, Vec<String>), String> {
    let table: toml::Table = toml::from_str(text).map_err(|e| e.to_string())?;
    patch_from_table(&table)
}

fn patch_from_table(table: &toml::Table) -> Result<(Patch, Vec<String>), String> {
    let mut patch = Patch::default();
    let mut warnings = Vec::new();
    let color = |key: &str, v: &toml::Value| -> Result<Rgb, String> {
        v.as_str()
            .and_then(parse_hex)
            .ok_or_else(|| format!("`{key}` must be a \"#rrggbb\" color"))
    };
    for (key, value) in table {
        match key.as_str() {
            "foreground" => patch.foreground = Some(color(key, value)?),
            "background" => patch.background = Some(color(key, value)?),
            "cursor" => patch.cursor = Some(color(key, value)?),
            "selection" | "selection_background" => patch.selection = Some(color(key, value)?),
            "ansi" => {
                let list = value.as_array().ok_or("`ansi` must be a list of colors")?;
                if list.len() > 16 {
                    warnings.push(format!(
                        "`ansi` has {} colors; only the first 16 are used",
                        list.len()
                    ));
                }
                for (i, v) in list.iter().take(16).enumerate() {
                    patch.colors.push((i as u8, color("ansi", v)?));
                }
            }
            "ui" => {
                let ui = value.as_table().ok_or("`[ui]` must be a table")?;
                for (k, v) in ui {
                    match k.as_str() {
                        "accent" => patch.accent = Some(color(k, v)?),
                        "sidebar" => patch.sidebar = Some(color(k, v)?),
                        other => warnings.push(format!("unknown key `ui.{other}`")),
                    }
                }
            }
            other => match other
                .strip_prefix("color")
                .and_then(|n| n.parse::<u8>().ok())
            {
                Some(i) => patch.colors.push((i, color(key, value)?)),
                None => warnings.push(format!("unknown key `{other}`")),
            },
        }
    }
    Ok((patch, warnings))
}

/// kitty theme format: `key value` per line, `#` comments. Unknown keys are ignored,
/// so full kitty configs and generated theme files both work.
pub fn parse_kitty(text: &str) -> Patch {
    let mut patch = Patch::default();
    for line in text.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let mut parts = line.split_whitespace();
        let (Some(key), Some(value)) = (parts.next(), parts.next()) else {
            continue;
        };
        let Some(rgb) = parse_hex(value) else {
            continue;
        };
        match key {
            "foreground" => patch.foreground = Some(rgb),
            "background" => patch.background = Some(rgb),
            "cursor" => patch.cursor = Some(rgb),
            "selection_background" => patch.selection = Some(rgb),
            "active_border_color" => patch.accent = Some(rgb),
            _ => {
                if let Some(i) = key.strip_prefix("color").and_then(|n| n.parse::<u8>().ok()) {
                    patch.colors.push((i, rgb));
                }
            }
        }
    }
    patch
}

/// Colors for the app chrome, derived from the theme so every theme (light or dark) works.
#[derive(Clone, Debug)]
pub struct UiColors {
    pub bg: Color32,
    pub fg: Color32,
    pub accent: Color32,
    pub bell: Color32,
    pub danger: Color32,
    /// Secondary accents (palette labels).
    pub purple: Color32,
    pub green: Color32,
    pub sidebar: Color32,
    pub light: bool,
}

fn c32([r, g, b]: Rgb) -> Color32 {
    Color32::from_rgb(r, g, b)
}

/// Linear blend from `a` to `b`.
pub fn mix(a: Color32, b: Color32, t: f32) -> Color32 {
    let l = |x: u8, y: u8| (x as f32 + (y as f32 - x as f32) * t).round() as u8;
    Color32::from_rgb(l(a.r(), b.r()), l(a.g(), b.g()), l(a.b(), b.b()))
}

impl UiColors {
    pub fn from_theme(t: &Theme) -> Self {
        let bg = c32(t.background);
        let light = t.is_light();
        Self {
            bg,
            fg: c32(t.foreground),
            accent: c32(t.accent.unwrap_or(t.colors[4])),
            bell: c32(t.colors[3]),
            danger: c32(t.colors[1]),
            purple: c32(t.colors[5]),
            green: c32(t.colors[2]),
            sidebar: t
                .sidebar
                .map(c32)
                .unwrap_or_else(|| mix(bg, Color32::BLACK, if light { 0.06 } else { 0.18 })),
            light,
        }
    }

    /// A surface raised above the terminal background by `t` (0 = background, 1 = foreground).
    pub fn raised(&self, t: f32) -> Color32 {
        mix(self.bg, self.fg, t)
    }

    /// A surface raised above the sidebar by `t`.
    pub fn raised_sidebar(&self, t: f32) -> Color32 {
        mix(self.sidebar, self.fg, t)
    }

    /// Something receding below the background (gaps between panes).
    pub fn recessed(&self, t: f32) -> Color32 {
        mix(self.bg, Color32::BLACK, t)
    }

    /// Black or white-ish text, whichever reads better on `bg`.
    pub fn readable_on(&self, bg: Color32) -> Color32 {
        let lum = 0.299 * bg.r() as f32 + 0.587 * bg.g() as f32 + 0.114 * bg.b() as f32;
        if lum > 150.0 {
            mix(Color32::BLACK, self.bg, 0.1)
        } else {
            Color32::WHITE
        }
    }
}

/// Collect the colors a shell set via OSC (the `Some` entries of alacritty's color table).
/// Indices 0-255 are the palette; 256/257/258 are foreground/background/cursor.
pub fn patch_from_osc(colors: &alacritty_terminal::term::color::Colors) -> Patch {
    use alacritty_terminal::vte::ansi::NamedColor;
    let rgb = |c: alacritty_terminal::vte::ansi::Rgb| [c.r, c.g, c.b];
    Patch {
        foreground: colors[NamedColor::Foreground].map(rgb),
        background: colors[NamedColor::Background].map(rgb),
        cursor: colors[NamedColor::Cursor].map(rgb),
        colors: (0..=255u8)
            .filter_map(|i| colors[i as usize].map(|c| (i, rgb(c))))
            .collect(),
        ..Default::default()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn builtins_parse_cleanly() {
        for (name, src) in BUILTIN {
            let (patch, warnings) = parse_toml(src).unwrap_or_else(|e| panic!("{name}: {e}"));
            assert!(warnings.is_empty(), "{name}: {warnings:?}");
            assert_eq!(patch.colors.len(), 16, "{name}");
        }
        assert!(!Theme::default().is_light());
    }

    #[test]
    fn toml_theme_with_color_n_and_ui() {
        let (p, warnings) = parse_toml(
            r##"
            background = "#101010"
            color4 = "#0000ff"
            color232 = "#121212"
            bogus = 1
            [ui]
            accent = "#ff00ff"
            "##,
        )
        .unwrap();
        assert_eq!(p.background, Some([0x10, 0x10, 0x10]));
        assert!(p.colors.contains(&(4, [0, 0, 0xff])));
        assert!(p.colors.contains(&(232, [0x12, 0x12, 0x12])));
        assert_eq!(p.accent, Some([0xff, 0, 0xff]));
        assert_eq!(warnings, vec!["unknown key `bogus`"]);
        assert!(parse_toml("background = \"red\"").is_err());
    }

    #[test]
    fn kitty_theme() {
        let p = parse_kitty(
            "# generated\nbackground            #1D1A18\nforeground #EDD4C2\ncolor1 #EF672C\n\
             color255 #DEC1B1\nselection_background #F4DED4\nfont_family Hack\ninclude other.conf\n",
        );
        assert_eq!(p.background, Some([0x1d, 0x1a, 0x18]));
        assert_eq!(p.foreground, Some([0xed, 0xd4, 0xc2]));
        assert_eq!(p.selection, Some([0xf4, 0xde, 0xd4]));
        assert_eq!(
            p.colors,
            vec![(1, [0xef, 0x67, 0x2c]), (255, [0xde, 0xc1, 0xb1])]
        );
    }

    #[test]
    fn merging_osc_patches() {
        let mut shell = Patch::default();
        shell.merge(Patch {
            background: Some([1, 1, 1]),
            colors: vec![(1, [9, 9, 9])],
            ..Default::default()
        });
        shell.merge(Patch {
            colors: vec![(1, [8, 8, 8]), (2, [7, 7, 7])],
            ..Default::default()
        });
        assert_eq!(shell.background, Some([1, 1, 1]));
        assert_eq!(shell.colors, vec![(1, [8, 8, 8]), (2, [7, 7, 7])]);
    }

    #[test]
    fn osc_overrides_become_a_patch() {
        use alacritty_terminal::term::color::Colors;
        use alacritty_terminal::vte::ansi::{NamedColor, Rgb as ARgb};
        let mut colors = Colors::default();
        assert!(patch_from_osc(&colors).is_empty());
        colors[4] = Some(ARgb { r: 1, g: 2, b: 3 });
        colors[NamedColor::Background] = Some(ARgb { r: 4, g: 5, b: 6 });
        let p = patch_from_osc(&colors);
        assert_eq!(p.colors, vec![(4, [1, 2, 3])]);
        assert_eq!(p.background, Some([4, 5, 6]));
    }

    #[test]
    fn layering_and_ui_derivation() {
        let mut t = Theme::default();
        assert_eq!(t.colors[16], [0, 0, 0]);
        assert_eq!(t.colors[231], [255, 255, 255]);
        t.apply(&parse_toml(BUILTIN[1].1).unwrap().0); // latte
        assert!(t.is_light());
        let ui = UiColors::from_theme(&t);
        assert!(ui.light);
        assert_eq!(ui.accent, Color32::from_rgb(0x1e, 0x66, 0xf5)); // falls back to color4
        // Raised surfaces move toward the foreground, so they get darker on a light theme.
        assert!(ui.raised(0.2).r() < ui.bg.r());
    }
}
